### ISSUE TITLE
Payout.

### ISSUE THREAD

**Issue by zek0** [FonWasH/esx_bumfight#2]
Problem with payout. (Easy money.) 2 fighters and 1 who bet. If im bet to fighter ex. 10000 after fight im recieve 20000. Thats problem.

Thank you.

**Comment by FonWasH** [comment]
I already thought about this problem, so i create 2 system.
1 - Rating system for fighter : for each fight fighters will win, less money bettor will win.
2 - Trust Score system for bettor : If they win some few suspicious bet the bookmaker will attack him and stop the possibility for the player to bet and he will be wanted by the bookmaker's gang.
